---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimum-weavegitops-role
rules:
- apiGroups: [""]
  resources: ["secrets","pods","events"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get","list"]
- apiGroups: ["kustomize.toolkit.fluxcd.io"]
  resources: ["kustomizations"]
  verbs: ["get","list"]
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get","list"]
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["*"]
  verbs: ["get","list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-test-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minimum-weavegitops-role
subjects:
  - kind: User
    name: gitops-test-user